// Diagnostic Tools JavaScript - Comprehensive monitoring and debugging suite

// Global state
const diagnosticState = {
    consoleLog: [],
    networkLog: [],
    requestCount: 0,
    errorCount: 0,
    performanceMonitoring: false,
    performanceInterval: null,
    testResults: [],
    healthCheckResults: {}
};

// Initialize on load
document.addEventListener('DOMContentLoaded', function() {
    // Set current date
    document.getElementById('current-date').textContent = new Date().toLocaleString();
    
    // Initialize system info
    updateSystemInfo();
    
    // Start console monitoring
    startConsoleMonitoring();
    
    // Start network monitoring
    startNetworkMonitoring();
    
    // Run initial health checks
    setTimeout(runHealthChecks, 1000);
    
    // Start performance monitoring
    startPerformanceMonitoring();
    
    // Log initialization
    addConsoleLog('info', 'Diagnostic tools initialized successfully');
    addNetworkLog('info', 'Monitoring services started');
});

// ========== CONSOLE ERROR CATCHER ==========

function startConsoleMonitoring() {
    const originalConsole = {
        log: console.log,
        error: console.error,
        warn: console.warn,
        info: console.info,
        debug: console.debug
    };

    // Override console methods
    console.log = function(...args) {
        originalConsole.log.apply(console, args);
        addConsoleLog('info', args.join(' '));
    };

    console.error = function(...args) {
        originalConsole.error.apply(console, args);
        addConsoleLog('error', args.join(' '));
        diagnosticState.errorCount++;
        updateErrorCount();
    };

    console.warn = function(...args) {
        originalConsole.warn.apply(console, args);
        addConsoleLog('warning', args.join(' '));
    };

    console.info = function(...args) {
        originalConsole.info.apply(console, args);
        addConsoleLog('info', args.join(' '));
    };

    console.debug = function(...args) {
        originalConsole.debug.apply(console, args);
        addConsoleLog('info', `[DEBUG] ${args.join(' ')}`);
    };
}

function addConsoleLog(type, message) {
    const timestamp = new Date().toLocaleTimeString();
    const logEntry = document.createElement('div');
    logEntry.className = `log-entry log-${type}`;
    logEntry.textContent = `[${timestamp}] ${message}`;
    
    const logContainer = document.getElementById('console-log');
    if (logContainer) {
        logContainer.appendChild(logEntry);
        logContainer.scrollTop = logContainer.scrollHeight;
        
        diagnosticState.consoleLog.push({ type, message, timestamp });
        
        // Keep only last 100 entries
        if (diagnosticState.consoleLog.length > 100) {
            diagnosticState.consoleLog.shift();
            if (logContainer.children.length > 100) {
                logContainer.removeChild(logContainer.firstChild);
            }
        }
    }
}

function clearConsoleLog() {
    const logContainer = document.getElementById('console-log');
    if (logContainer) {
        logContainer.innerHTML = 
            '<div class="log-entry log-info">[Cleared] Console log cleared</div>';
        diagnosticState.consoleLog = [];
        addConsoleLog('info', 'Console log cleared');
    }
}

function testConsoleError() {
    console.error('Test error generated by diagnostic tools');
}

function testConsoleWarning() {
    console.warn('Test warning generated by diagnostic tools');
}

// ========== NETWORK REQUEST MONITOR ==========

function startNetworkMonitoring() {
    // Monitor fetch API
    const originalFetch = window.fetch;
    
    window.fetch = function(...args) {
        const startTime = Date.now();
        const requestId = diagnosticState.requestCount + 1;
        diagnosticState.requestCount++;
        
        const url = typeof args[0] === 'string' ? args[0] : args[0].url;
        const method = args[1]?.method || 'GET';
        
        addNetworkLog('info', `→ ${method} ${url}`);
        updateRequestCount();
        
        return originalFetch.apply(this, args)
            .then(response => {
                const duration = Date.now() - startTime;
                addNetworkLog('success', `← ${response.status} ${response.statusText} (${duration}ms)`);
                return response;
            })
            .catch(error => {
                const duration = Date.now() - startTime;
                diagnosticState.errorCount++;
                addNetworkLog('error', `✗ ${error.message} (${duration}ms)`);
                updateErrorCount();
                throw error;
            });
    };

    // Monitor XMLHttpRequest
    const originalXHROpen = XMLHttpRequest.prototype.open;
    const originalXHRSend = XMLHttpRequest.prototype.send;
    
    XMLHttpRequest.prototype.open = function(method, url) {
        this._requestMethod = method;
        this._requestUrl = url;
        this._startTime = Date.now();
        return originalXHROpen.apply(this, arguments);
    };
    
    XMLHttpRequest.prototype.send = function(body) {
        diagnosticState.requestCount++;
        
        addNetworkLog('info', `→ ${this._requestMethod} ${this._requestUrl}`);
        updateRequestCount();
        
        this.addEventListener('load', function() {
            const duration = Date.now() - this._startTime;
            addNetworkLog('success', `← ${this.status} (${duration}ms)`);
        });
        
        this.addEventListener('error', function() {
            const duration = Date.now() - this._startTime;
            diagnosticState.errorCount++;
            addNetworkLog('error', `✗ Request failed (${duration}ms)`);
            updateErrorCount();
        });
        
        return originalXHRSend.apply(this, arguments);
    };
}

function addNetworkLog(type, message) {
    const timestamp = new Date().toLocaleTimeString();
    const logEntry = document.createElement('div');
    logEntry.className = `log-entry log-${type}`;
    logEntry.textContent = `[${timestamp}] ${message}`;
    
    const logContainer = document.getElementById('network-log');
    if (logContainer) {
        logContainer.appendChild(logEntry);
        logContainer.scrollTop = logContainer.scrollHeight;
        
        diagnosticState.networkLog.push({ type, message, timestamp });
        
        // Keep only last 100 entries
        if (diagnosticState.networkLog.length > 100) {
            diagnosticState.networkLog.shift();
            if (logContainer.children.length > 100) {
                logContainer.removeChild(logContainer.firstChild);
            }
        }
    }
}

function clearNetworkLog() {
    const logContainer = document.getElementById('network-log');
    if (logContainer) {
        logContainer.innerHTML = 
            '<div class="log-entry log-info">[Cleared] Network log cleared</div>';
        diagnosticState.networkLog = [];
        addNetworkLog('info', 'Network log cleared');
    }
}

function updateRequestCount() {
    const element = document.getElementById('request-count');
    if (element) {
        element.textContent = diagnosticState.requestCount;
    }
}

function updateErrorCount() {
    const element = document.getElementById('error-count');
    if (element) {
        element.textContent = diagnosticState.errorCount;
    }
}

function testNetworkRequest() {
    // Test with a request to a non-existent endpoint
    fetch('/api/test-endpoint-' + Date.now())
        .catch(error => {
            // Expected error
        });
}

// ========== REACT COMPONENT DEBUGGER ==========

function refreshComponentTree() {
    const tree = document.getElementById('component-tree');
    if (!tree) return;
    
    tree.innerHTML = `
        <div class="component-node">App (Root)</div>
        <div class="component-props">props: &#123;theme: "light", version: "1.0.0"&#125;</div>
        <div class="component-node" style="margin-left: 1rem;">Router</div>
        <div class="component-node" style="margin-left: 2rem;">MainLayout</div>
        <div class="component-props" style="margin-left: 3rem;">props: &#123;user: "admin", permissions: ["read", "write"]&#125;</div>
        <div class="component-node" style="margin-left: 3rem;">Sidebar</div>
        <div class="component-props" style="margin-left: 4rem;">props: &#123;collapsed: false, items: 8&#125;</div>
        <div class="component-node" style="margin-left: 3rem;">Dashboard</div>
        <div class="component-props" style="margin-left: 4rem;">props: &#123;data: "[...]", loading: false&#125;</div>
        <div class="component-node" style="margin-left: 4rem;">ChartComponent</div>
        <div class="component-props" style="margin-left: 5rem;">props: &#123;type: "line", dataPoints: 24&#125;</div>
    `;
    addConsoleLog('info', 'Component tree refreshed');
}

function simulateComponentUpdate() {
    addConsoleLog('info', 'Simulating component update...');
    setTimeout(() => {
        addConsoleLog('success', 'Component update completed');
        refreshComponentTree();
    }, 500);
}

// ========== DEPLOYMENT STATUS CHECKER ==========

async function runHealthChecks() {
    const deploymentStatus = document.getElementById('deployment-status');
    if (deploymentStatus) {
        deploymentStatus.textContent = 'Checking...';
        deploymentStatus.className = 'status-badge status-warning';
    }
    
    const checks = [
        { id: 'backend-status', url: '/api/health', name: 'Backend API' },
        { id: 'database-status', url: '/api/health/db', name: 'Database' },
        { id: 'auth-status', url: '/api/auth/health', name: 'Authentication Service' }
    ];
    
    let allHealthy = true;
    
    for (const check of checks) {
        const element = document.getElementById(check.id);
        if (!element) continue;
        
        element.textContent = 'Checking...';
        element.style.color = '#f59e0b';
        
        try {
            // Simulate API check (in real implementation, this would be actual fetch)
            await new Promise(resolve => setTimeout(resolve, 300 + Math.random() * 700));
            
            // Simulate 85% success rate
            const isHealthy = Math.random() > 0.15;
            
            if (isHealthy) {
                element.textContent = '✅ Online';
                element.style.color = '#10b981';
                diagnosticState.healthCheckResults[check.name] = { status: 'healthy', timestamp: new Date() };
                addConsoleLog('success', `${check.name} health check passed`);
            } else {
                element.textContent = '❌ Offline';
                element.style.color = '#ef4444';
                diagnosticState.healthCheckResults[check.name] = { status: 'unhealthy', timestamp: new Date() };
                addConsoleLog('error', `${check.name} health check failed`);
                allHealthy = false;
            }
        } catch (error) {
            element.textContent = '❌ Error';
            element.style.color = '#ef4444';
            diagnosticState.healthCheckResults[check.name] = { status: 'error', timestamp: new Date(), error: error.message };
            addConsoleLog('error', `${check.name} health check error: ${error.message}`);
            allHealthy = false;
        }
    }
    
    // Update deployment status
    if (deploymentStatus) {
        if (allHealthy) {
            deploymentStatus.textContent = 'Healthy';
            deploymentStatus.className = 'status-badge status-active';
            addConsoleLog('success', 'All health checks passed');
        } else {
            deploymentStatus.textContent = 'Degraded';
            deploymentStatus.className = 'status-badge status-warning';
            addConsoleLog('warning', 'Some services are experiencing issues');
        }
    }
}

function checkDeploymentStatus() {
    addConsoleLog('info', 'Checking deployment status...');
    // Simulate deployment check
    setTimeout(() => {
        const statuses = ['Deployed', 'Building', 'Failed', 'Pending'];
        const randomStatus = statuses[Math.floor(Math.random() * statuses.length)];
        
        addConsoleLog('info', `Deployment status: ${randomStatus}`);
        alert(`Deployment Status: ${randomStatus}\n\nLast deployment: 2 hours ago\nNext deployment: Scheduled for maintenance window`);
    }, 800);
}

// ========== AUTOMATED TEST SUITE ==========

async function runAllTests() {
    const testStatus = document.getElementById('test-status');
    if (testStatus) {
        testStatus.textContent = 'Running...';
        testStatus.className = 'status-badge status-warning';
    }
    
    const testResults = document.getElementById('test-results');
    if (!testResults) return;
    
    testResults.innerHTML = '';
    diagnosticState.testResults = [];
    
    const tests = [
        { name: 'Authentication Tests', category: 'auth', duration: 800 },
        { name: 'API Integration Tests', category: 'api', duration: 1200 },
        { name: 'UI Component Tests', category: 'ui', duration: 1500 },
        { name: 'Performance Tests', category: 'perf', duration: 2000 },
        { name: 'Security Tests', category: 'security', duration: 1000 },
        { name: 'Database Tests', category: 'db', duration: 900 }
    ];
    
    for (const test of tests) {
        const testElement = document.createElement('div');
        testElement.className = 'test-case';
        testElement.innerHTML = `
            <strong>⏳ ${test.name}</strong>
            <div style="font-size: 0.875rem; color: #64748b;">Running...</div>
        `;
        testResults.appendChild(testElement);
        
        // Simulate test execution
        await new Promise(resolve => setTimeout(resolve, test.duration));
        
        // Simulate 90% pass rate
        const passed = Math.random() > 0.1;
        
        testElement.className = `test-case ${passed ? 'test-pass' : 'test-fail'}`;
        testElement.innerHTML = `
            <strong>${passed ? '✓' : '✗'} ${test.name}</strong>
            <div style="font-size: 0.875rem; color: #64748b;">
                ${passed ? 'All tests passed' : 'Some tests failed'} (${test.duration}ms)
            </div>
        `;
        
        diagnosticState.testResults.push({
            name: test.name,
            passed,
            duration: test.duration,
            timestamp: new Date()
        });
        
        addConsoleLog(passed ? 'success' : 'error', 
            `${test.name}: ${passed ? 'PASSED' : 'FAILED'}`);
    }
    
    if (testStatus) {
        testStatus.textContent = 'Completed';
        testStatus.className = 'status-badge status-active';
    }
    addConsoleLog('info', 'All tests completed');
}

function runComponentTests() {
    addConsoleLog('info', 'Running component tests...');
    // Simulate component tests
    setTimeout(() => {
        addConsoleLog('success', 'Component tests completed: 24/24 passed');
        alert('Component Tests Results:\n\n✓ 24 tests passed\n✓ 0 tests failed\n✓ 100% coverage\n\nAll components are functioning correctly.');
    }, 1500);
}

function runIntegrationTests() {
    addConsoleLog('info', 'Running integration tests...');
    // Simulate integration tests
    setTimeout(() => {
        addConsoleLog('success', 'Integration tests completed: 18/18 passed');
        alert('Integration Tests Results:\n\n✓ 18 tests passed\n✓ 0 tests failed\n✓ All API endpoints responding\n\nSystem integration is stable.');
    }, 2000);
}

// ========== PERFORMANCE MONITOR ==========

function startPerformanceMonitoring() {
    if (diagnosticState.performanceMonitoring) return;
    
    diagnosticState.performanceMonitoring = true;
    const performanceStatus = document.getElementById('performance-status');
    if (performanceStatus) {
        performanceStatus.textContent = 'Active';
    }
    
    // FPS counter
    let lastTime = Date.now();
    let frames = 0;
    
    diagnosticState.performanceInterval = setInterval(() => {
        // Update FPS
        frames++;
        const now = Date.now();
        if (now >= lastTime + 1000) {
            const fps = Math.round((frames * 1000) / (now - lastTime));
            const fpsElement = document.getElementById('fps-counter');
            if (fpsElement) fpsElement.textContent = fps;
            frames = 0;
            lastTime = now;
        }
        
        // Update memory usage
        const memoryElement = document.getElementById('memory-usage');
        if (memoryElement) {
            if (performance.memory) {
                const usedMB = Math.round(performance.memory.usedJSHeapSize / 1048576);
                const totalMB = Math.round(performance.memory.totalJSHeapSize / 1048576);
                memoryElement.textContent = `${usedMB}/${totalMB} MB`;
            } else {
                // Fallback simulation
                const simulatedUsage = 80 + Math.random() * 40;
                memoryElement.textContent = `${Math.round(simulatedUsage)} MB`;
            }
        }
        
        // Update CPU usage (simulated)
        const cpuElement = document.getElementById('cpu-usage');
        if (cpuElement) {
            const cpuUsage = 10 + Math.random() * 40;
            cpuElement.textContent = `${Math.round(cpuUsage)}%`;
        }
        
        // Update load time on first run
        const loadTimeElement = document.getElementById('load-time');
        if (loadTimeElement && loadTimeElement.textContent === '--') {
            const loadTime = performance.timing ? 
                performance.timing.loadEventEnd - performance.timing.navigationStart : 
                1200 + Math.random() * 800;
            loadTimeElement.textContent = Math.round(loadTime);
        }
    }, 100);
}

function stopPerformanceMonitoring() {
    if (diagnosticState.performanceInterval) {
        clearInterval(diagnosticState.performanceInterval);
        diagnosticState.performanceInterval = null;
    }
    diagnosticState.performanceMonitoring = false;
    
    const performanceStatus = document.getElementById('performance-status');
    if (performanceStatus) {
        performanceStatus.textContent = 'Stopped';
        performanceStatus.className = 'status-badge status-warning';
    }
    addConsoleLog('info', 'Performance monitoring stopped');
}

function exportMetrics() {
    const metrics = {
        memory: document.getElementById('memory-usage')?.textContent || '--',
        cpu: document.getElementById('cpu-usage')?.textContent || '--',
        fps: document.getElementById('fps-counter')?.textContent || '--',
        loadTime: document.getElementById('load-time')?.textContent || '--',
        timestamp: new Date().toISOString()
    };
    
    const dataStr = JSON.stringify(metrics, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
    
    const exportFileDefaultName = `performance-metrics-${new Date().toISOString().slice(0, 10)}.json`;
    
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
    
    addConsoleLog('info', 'Performance metrics exported');
}

// ========== SYSTEM INFORMATION ==========

function updateSystemInfo() {
    // Browser info
    const browserElement = document.getElementById('browser-info');
    if (browserElement) {
        browserElement.textContent = getBrowserInfo();
    }
    
    // Screen resolution
    const screenElement = document.getElementById('screen-res');
    if (screenElement) {
        screenElement.textContent = `${window.screen.width}×${window.screen.height}`;
    }
    
    // Connection type
    const connectionElement = document.getElementById('connection-type');
    if (connectionElement) {
        connectionElement.textContent = navigator.connection ? 
            navigator.connection.effectiveType || 'Unknown' : 'Unknown';
    }
    
    // Timezone
    const timezoneElement = document.getElementById('timezone');
    if (timezoneElement) {
        timezoneElement.textContent = Intl.DateTimeFormat().resolvedOptions().timeZone;
    }
}

function getBrowserInfo() {
    const ua = navigator.userAgent;
    let browser = "Unknown";
    
    if (ua.includes("Chrome") && !ua.includes("Edg")) {
        browser = "Chrome";
    } else if (ua.includes("Firefox")) {
        browser = "Firefox";
    } else if (ua.includes("Safari") && !ua.includes("Chrome")) {
        browser = "Safari";
    } else if (ua.includes("Edg")) {
        browser = "Edge";
    }
    
    return browser;
}

// ========== UTILITY FUNCTIONS ==========

function exportAllLogs() {
    const allData = {
        consoleLog: diagnosticState.consoleLog,
        networkLog: diagnosticState.networkLog,
        testResults: diagnosticState.testResults,
        healthCheckResults: diagnosticState.healthCheckResults,
        metrics: {
            requestCount: diagnosticState.requestCount,
            errorCount: diagnosticState.errorCount,
            performanceMonitoring: diagnosticState.performanceMonitoring
        },
        systemInfo: {
            browser: getBrowserInfo(),
            screenResolution: `${window.screen.width}×${window.screen.height}`,
            timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
            userAgent: navigator.userAgent
        },
        exportTimestamp: new Date().toISOString()
    };
    
    const dataStr = JSON.stringify(allData, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
    
    const exportFileDefaultName = `diagnostic-logs-${new Date().toISOString().slice(0, 10)}.json`;
    
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
    
    addConsoleLog('info', 'All diagnostic logs exported');
}

function resetAll() {
    if (confirm('Are you sure you want to reset all diagnostic data? This cannot be undone.')) {
        // Clear console log
        clearConsoleLog();
        
        // Clear network log
        clearNetworkLog();
        
        // Reset counters
        diagnosticState.requestCount = 0;
        diagnosticState.errorCount = 0;
        updateRequestCount();
        updateErrorCount();
        
        // Clear test results
        const testResults = document.getElementById('test-results');
        if (testResults) {
            testResults.innerHTML = `
                <div class="test-case">
                    <strong>○ Authentication Tests</strong>
                    <div style="font-size: 0.875rem; color: #64748b;">Login, logout, token validation</div>
                </div>
                <div class="test-case">
                    <strong>○ API Integration Tests</strong>
                    <div style="font-size: 0.875rem; color: #64748b;">Endpoints, error handling, rate limiting</div>
                </div>
                <div class="test-case">
                    <strong>○ UI Component Tests</strong>
                    <div style="font-size: 0.875rem; color: #64748b;">Render, interactions, accessibility</div>
                </div>
                <div class="test-case">
                    <strong>○ Performance Tests</strong>
                    <div style="font-size: 0.875rem; color: #64748b;">Load times, memory usage, responsiveness</div>
                </div>
            `;
        }
        
        // Reset health checks
        const healthElements = ['backend-status', 'database-status', 'auth-status'];
        healthElements.forEach(id => {
            const element = document.getElementById(id);
            if (element) {
                element.textContent = 'Checking...';
                element.style.color = '';
            }
        });
        
        // Reset deployment status
        const deploymentStatus = document.getElementById('deployment-status');
        if (deploymentStatus) {
            deploymentStatus.textContent = 'Checking...';
            deploymentStatus.className = 'status-badge status-warning';
        }
        
        // Reset test status
        const testStatus = document.getElementById('test-status');
        if (testStatus) {
            testStatus.textContent = 'Ready';
            testStatus.className = 'status-badge status-active';
        }
        
        // Clear state
        diagnosticState.testResults = [];
        diagnosticState.healthCheckResults = {};
        
        addConsoleLog('info', 'All diagnostic data has been reset');
    }
}

// ========== REACT INTEGRATION HELPERS ==========

// These functions would be integrated into a React application
function integrateWithReact(app) {
    // In a real React app, this would set up React DevTools integration
    console.log('React integration available for:', app);
    
    // Example: Monkey-patch React.createElement to track component creation
    if (window.React && window.React.createElement) {
        const originalCreateElement = window.React.createElement;
        window.React.createElement = function(type, props, ...children) {
            // Track component creation
            const componentName = type.displayName || type.name || 'Anonymous';
            addConsoleLog('info', `React component created: ${componentName}`);
            
            return originalCreateElement.call(this, type, props, ...children);
        };
    }
}

// ========== ERROR BOUNDARY INTEGRATION ==========

class DiagnosticErrorBoundary {
    constructor() {
        this.errors = [];
    }
    
    catch(error, errorInfo) {
        const errorData = {
            error: error.toString(),
            stack: error.stack,
            componentStack: errorInfo?.componentStack,
            timestamp: new Date().toISOString()
        };
        
        this.errors.push(errorData);
        
        // Log to console
        console.error('React Error Boundary caught:', error);
        console.error('Component stack:', errorInfo?.componentStack);
        
        // Add to diagnostic logs
        addConsoleLog('error', `React Error: ${error.toString()}`);
        
        return errorData;
    }
    
    getErrors() {
        return this.errors;
    }
    
    clearErrors() {
        this.errors = [];
    }
}

// Export for use in React apps
window.DiagnosticTools = {
    startConsoleMonitoring,
    startNetworkMonitoring,
    startPerformanceMonitoring,
    stopPerformanceMonitoring,
    runHealthChecks,
    runAllTests,
    exportAllLogs,
    resetAll,
    integrateWithReact,
    ErrorBoundary: DiagnosticErrorBoundary,
    getState: () => ({ ...diagnosticState })
};